[general]
import = ["./themes/themes/nord.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "tmux-256color"

[font]
size = 12.0

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[font.bold]
family = "Cascadia Code"
style = "Bold"

[font.bold_italic]
family = "Cascadia Code"
style = "Bold Italic"

[font.italic]
family = "Cascadia Code"
style = "Italic"

[font.normal]
family = "Cascadia Code"
style = "Regular"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[mouse]
hide_when_typing = false

[scrolling]
history = 100000
multiplier = 3

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/usr/bin/fish"

[window]
decorations = "Buttonless"
dynamic_padding = false
dynamic_title = true
startup_mode = "Maximized"
opacity = 0.9
blur = true

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[terminal]
